[pytest]

# Parametros que serán utilizados por pytest para ejecutar las pruebas. Estos parámetros se pueden configurar en el archivo pytest.ini para personalizar el comportamiento de pytest:


# Archivos a ejecutar, todos los que comiencen con test_*.py (* indicaque "ejecute todos los test")
python_files = test_*.py    

# Patrones de clases de pruebas
python_classes = Test*

# Patron de funciones de pruebas
python_functions = test_*


# Parametros adicionales para ejecutar las pruebas desde la consola
addopts = -v --html=report.html --self-contained-html
    # -v: Modo detallado para mostrar más información durante la ejecución de las pruebas.
    # --html=report.html: Genera un reporte en formato HTML con el nombre "report.html".
    # --self-contained-html: Incluye todos los recursos necesarios (CSS, JavaScript) dentro del archivo HTML generado, lo que permite compartir el reporte sin preocuparse por archivos adicionales.



markers =
    smoke: pruebas criticas del sistema
    regression: pruebas de regresión
    api: pruebas de API
    ui: pruebas de interfaz
    # registro los marcadores o etiquetas de mi proyecto para que pytest las reconozca.
    # así se evitan los warnings al ejecutar el test. Los warning avisan que algo podría no estar configurado del todo bien.

